/** Shape of `public/data/gtec_tertiary.json` (generated by `scripts/merge_gtec_csv.py`). */

export type GtecProgrammeRow = {
  name: string;
  duration_years: number | null;
  status: string | null;
};

export type GtecInstitution = {
  id: string;
  name: string;
  programmes: GtecProgrammeRow[];
};

export type GtecCategoryKey = "university" | "technical_university" | "other_tertiary";

export type GtecPayload = {
  source: string;
  generated_at: string;
  file_count: number;
  categories: Record<GtecCategoryKey, GtecInstitution[]>;
};
